import './globals.css'
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import { NextAuthProvider } from './providers'

const inter = Nunito({
  subsets: ['latin'],
  variable: '--font-nunito',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${inter.variable} font-sans antialiased`}>
      <body>
        <NextAuthProvider>
          <main>{children}</main>
        </NextAuthProvider>
        <ToastContainer />
      </body>
    </html>
  )
}
